#!/usr/bin/env node

/**
 * This script updates the version.ts file to match the version in package.json
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get current directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read package.json
const packageJsonPath = path.resolve(__dirname, '../package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

// Update version.ts
const versionTsPath = path.resolve(__dirname, '../src/version.ts');
const versionTsContent = `// This file is auto-generated by scripts/update-version.js
// Do not edit this file manually

/**
 * Package version from package.json
 */
const VERSION = '${version}';
export default VERSION;
`;

// Write the file
fs.writeFileSync(versionTsPath, versionTsContent);

console.log(`Updated version.ts to version ${version}`);
